name: Build Mac App

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-mac:
    runs-on: macos-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.8.0' 

      - name: Install dependencies
        run: npm install

      - name: Build Mac App
        # Explicitno mu zabranjujemo da pokušava publish (-p never)
        run: npm run build && npx electron-builder --mac -p never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload .dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: Restless-Mac-App
          path: release/*.dmg